In [1]:
import numpy as np
import pandas as pd

# Question 1

**What's the version of Pandas that you installed?**

In [2]:
pd.__version__

'2.1.0'

**Getting the data**

In [3]:
!wget -c https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 19:57:18--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1,4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1,36M  4,96MB/s    in 0,3s    

2023-09-17 19:57:19 (4,96 MB/s) - ‘housing.csv’ saved [1423529/1423529]



**Load the data**

In [4]:
df = pd.read_csv("housing.csv")

# Question 2

**How many columns are in the dataset?**

In [5]:
len(df.columns)

10

# Question 3

**Which columns in the dataset have missing values?**

In [6]:
df.isna().sum() # total_bedrooms

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4

**How many unique values does the `ocean_proximity` column have?**

In [7]:
df["ocean_proximity"].nunique()

5

# Question 5

**What's the average value of the `median_house_value` for the houses located near the bay?**

In [8]:
filter = df["ocean_proximity"] == "NEAR BAY"
int(df[filter].median_house_value.mean())

259212

# Question 6

1. **Calculate the average of `total_bedrooms` column in the dataset.**
2. **Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.**
3. **Now, calculate the average of `total_bedrooms` again.**
4. **Has it changed?**

**1. Average of `total_bedrooms` column**

In [9]:
tb_avg = df["total_bedrooms"].mean()
print(f"AVG(total_bedrooms): {tb_avg.round(3)}")

AVG(total_bedrooms): 537.871


**2. Filling in `na`-values**

In [10]:
df["total_bedrooms"].fillna(value=tb_avg, inplace=True)
print("Number of NA-Values: ", df["total_bedrooms"].isna().sum())

Number of NA-Values:  0


**3. Recalculation of 1. with fixed NA-Values**

In [11]:
tb_avg_fixed = df["total_bedrooms"].mean()
print(f"AVG(total_bedrooms): {tb_avg_fixed.round(3)}")

AVG(total_bedrooms): 537.871


**4. Has the result changed?**

- No
- Additional samples that exactly lie in the mean of a distribution do not change the mean of the whole distribution.

# Question 7

1. **Select all the options located on islands.**
2. **Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.**
3. **Get the underlying NumPy array. Let's call it `X`.**
4. **Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.**
5. **Compute the inverse of `XTX`.**
6. **Create an array `y` with values `[950, 1300, 800, 1000, 1300]`**.
7. **Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.**
8. **What's the value of the last element of `w`?**

**1. Select all the options located on islands.**

In [12]:
df_island = df[df["ocean_proximity"] == "ISLAND"]
print(len(df_island))
df_island

5


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

**2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.**

In [13]:
df_subset = df_island[["housing_median_age", "total_rooms", "total_bedrooms"]]
df_subset

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

**3. Get the underlying NumPy array. Let's call it `X`.**

In [14]:
X = df_subset.values
print(X.shape)
print(X)

(5, 3)
[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


**4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.**

In [15]:
XTX = X.T @ X
print("X.T @ X: ", XTX.shape)

X.T @ X:  (3, 3)


**5. Compute the inverse of `XTX`.**

In [16]:
inv_XTX = np.linalg.inv(XTX)
print("XTX⁻¹: ", inv_XTX.shape)

XTX⁻¹:  (3, 3)


**6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`**.

In [17]:
y = np.array([950, 1300, 800, 1000, 1300])
print("y: ", y.shape)

y:  (5,)


**7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.**

In [18]:
w = inv_XTX @ X.T @ y
print(f"Shapes: {w.shape} = {inv_XTX.shape} x {X.T.shape} x {y.shape}")

Shapes: (3,) = (3, 3) x (3, 5) x (5,)


**8. What's the value of the last element of `w`?**

In [19]:
print(f"{w[-1]:.4f}")

5.6992
