# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [2]:
import numpy as np

## Vector operations

In [4]:
u = np.array([2, 4, 5, 6])
print(u.shape)

(4,)


In [6]:
# Elementwise scalar multiclation of vector (uses broadcasting -> scalar broadcased to fit vector-size)
2 * u

array([ 4,  8, 10, 12])

In [7]:
v = np.array([1, 0, 0, 2])
print(v.shape)

(4,)


In [8]:
# Element wise addition
u + v

array([3, 4, 5, 8])

In [7]:
# Element wise multiplication
u * v

array([ 2,  0,  0, 12])

## Multiplication

In [9]:
v.shape[0]

4

In [10]:
def vector_vector_multiplication(u: np.ndarray, v: np.ndarray) -> np.ndarray:
    assert u.shape[0] == v.shape[0] # Vectors must have same size
    
    n: int = u.shape[0]
    
    result: float = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

Vector x Vector Multiplication is the **Scalar-Product / Dot-Product**: $u^T v = \sum_{i=1}^n u_i\cdot v_i$

In [12]:
vector_vector_multiplication(u, v)

14.0

In [13]:
u.dot(v)

14

In [16]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [17]:
U.shape

(3, 4)

**Matrix-Vector multiplication**

In Matrix-Vector multiplication the dimensions are crucial.
- $U\in\mathbb{R}^{n\times m}$
- $v\in\mathbb{R}^m$
- $Uv = x\in\mathbb{R}^{m}$

In [18]:
# Manual solution that does not explicitely use the numpy matrix-vector multiplication
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [19]:
x = matrix_vector_multiplication(U, v)
print(x.shape)
x

(3,)


array([14.,  5.,  5.])

In [20]:
# Dot-Product from vector-vector multiplication can also be used for matrix-vector multiplication
U.dot(v)

array([14,  5,  5])

In [22]:
# Alternative to `dot`
U @ v

array([14,  5,  5])

**Matrix-Matrix-Multiplication**

In [31]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])


- Compuations in matrix-matrix computations
    - $U\in\mathbb{R}^{n\times m}$
    - $V\in\mathbb{R}^{m\times p}$
    - $UV = W \in\mathbb{R}^{n\times p}$

In [32]:
print("U: ", U.shape)
print("V: ", V.shape)

U:  (3, 4)
V:  (4, 3)


In [33]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [35]:
W = matrix_matrix_multiplication(U, V)
print(f"{U.shape} x {V.shape} = {W.shape}")
W

(3, 4) x (4, 3) = (3, 3)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [36]:
W = U.dot(V)
print(f"{U.shape} x {V.shape} = {W.shape}")
W

(3, 4) x (4, 3) = (3, 3)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [39]:
I = np.eye(3)
print(I.shape)

(3, 3)


In [40]:
print(V.shape)
V

(4, 3)


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [41]:
VI = V.dot(I)
print(f"{V.shape} x {I.shape} = {VI.shape}")
VI

(4, 3) x (3, 3) = (4, 3)


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [42]:
Vs = V[[0, 1, 2]]
print(Vs.shape)
Vs

(3, 3)


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [43]:
Vs_inv = np.linalg.inv(Vs)
print(Vs_inv.shape)
Vs_inv

(3, 3)


array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

**Property of inverse of a matrix:**
- $X^{-1}X = I$

In [34]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas